// Generated by LiveScript 1.4.0
(function(){
  var width, height, renderer, stage, animate;
  width = 1000;
  height = 600;
  renderer = new PIXI.autoDetectRenderer(width, height, {
    antialias: true
  });
  stage = new PIXI.Container();
  window.trystal = new Trystal(width, height);
  stage.addChild(trystal.container);
  document.onkeydown = function(e){
    e = e || window.event;
    switch (e.which || e.keyCode) {
    case 37:
    case 65:
      trystal.shiftFalling(-1);
      break;
    case 38:
    case 87:
      trystal.rotate(1);
      break;
    case 39:
    case 68:
      trystal.shiftFalling(1);
      break;
    case 40:
    case 83:
      trystal.rotate(-1);
    }
    e.preventDefault;
  };
  trystal.newFalling();
  animate = function(timestamp){
    trystal.container.rotation = (trystal.container.rotation + 0.001) % (Math.PI / 4);
    trystal.dropFalling();
    renderer.render(stage);
    return requestAnimationFrame(animate);
  };
  animate();
  setInterval(function(){
    trystal.newFalling();
  }, 500);
  document.body.appendChild(renderer.view);
}).call(this);
