// Generated by LiveScript 1.4.0
(function(){
  PIXI.Matrix.prototype.applyFlat = function(points){
    var newPoints, i$, len$, i, x, y;
    newPoints = [];
    for (i$ = 0, len$ = points.length; i$ < len$; i$ += 2) {
      i = i$;
      x = points[i];
      y = points[i + 1];
      newPoints[i] = this.a * x + this.c * y + this.tx;
      newPoints[i + 1] = this.b * x + this.d * y + this.ty;
    }
    return newPoints;
  };
}).call(this);
